# Generated by Django 3.2 on 2021-04-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210427_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': '4. Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeattribute',
            options={'verbose_name_plural': '5. EmployeesAttributes'},
        ),
    ]
