# Generated by Django 3.1.4 on 2021-05-08 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210508_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='countdown',
        ),
        migrations.AddField(
            model_name='project',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
